server:
  port: 8083
  
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sub
    url: jdbc:h2:mem:testdb
    username: sub
    
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
